server:
  port: 8080
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/queuerite
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
  main:
    web-application-type: none


